// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ChatSidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<aside id=\"chat-sidebar\" class=\"bg-secondary text-text w-64 min-h-screen p-4 flex flex-col fixed top-0 right-0 shadow-lg\"><!-- Header --><div class=\"mb-4 flex items-center justify-between\"><h2 class=\"text-2xl font-bold text-accent\">Chat</h2><button class=\"text-accent hover:text-accent-dark transition-colors duration-200\" id=\"close-chat-sidebar\" hx-get=\"/\" hx-target=\"#chat-sidebar\">✖</button></div><!-- Chat Messages --><div id=\"chat-messages\" class=\"flex-grow overflow-y-auto space-y-2 border-b border-secondary mb-4 p-2\"><!-- Example message --><div class=\"bg-primary p-2 rounded-lg shadow\"><p class=\"text-sm\"><strong>User1:</strong> Hey there! How's it going?</p></div><div class=\"bg-accent p-2 rounded-lg shadow self-end text-primary\"><p class=\"text-sm\"><strong>You:</strong> All good here. What about you?</p></div><!-- Add more chat messages here --></div><!-- Input Box --><div class=\"flex items-center space-x-2\"><input type=\"text\" id=\"chat-input\" class=\"flex-grow p-2 border rounded bg-primary text-text\" placeholder=\"Type a message...\"> <button id=\"send-message\" class=\"py-2 px-4 bg-accent text-primary rounded hover:bg-opacity-80 transition-colors duration-200\" hx-post=\"/send-message\" hx-vals=\"{&#39;message&#39;: document.getElementById(&#39;chat-input&#39;).value}\" hx-target=\"#chat-messages\">Send</button></div><script>\n            //window.alexdunmow.initChatSidebar();\n        </script></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
